### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by codekipple** [eduardoboucas/include-media-export#2]
Hi Eduardo,

Just wanted to ask what kind of browser support your aiming for with this? I was trying to build a similar thing a while back and ran into issues with ie8 and some older version on android not being able to read the contents on the :after or :before pseudo elements. See this question I posted http://stackoverflow.com/questions/12959199/how-can-i-capture-after-content-in-ie8/13138505#13138505

In the end I found this project https://github.com/JoshBarr/on-media-query which started using the font-family property instead to get around these issues. I used it a few times but went back to declaring my breakpoints in both styles and javascript. By the looks of it that project has been abandoned a bit.

Things may be at a point where the browsers that cannot read the contents on the :after or :before pseudo elements no longer matter but I thought i'd give you a heads up incase you were not familiar with JoshBarr's project. 

Carl.

**Comment by codekipple** [comment]
Actually thinking about it I wonder if the support for reading these values nicely overlaps with support with media queries. Back when I was trying to do this before I was serving respond.js to ie8 to emulate media queries. I have since learnt the error of my ways and now no longer try to polyfill media queries.

So the dream of declaring media queries once might be back on for me! I'll have to give your script a run and do some mobile testing. I'll let you know if I find anything interesting :)

**Comment by eduardoboucas** [comment]
@codekipple thanks for the heads up. [This article](https://css-tricks.com/making-sass-talk-to-javascript-with-json/) also describes how the `font-family` property in the `<head>` can be used, so it's definitely something we can add to this script if it allows more people to use this script.

Let me know how you get on with your tests.

Thanks!
